name: flutter_blue
description: Flutter plugin for connecting and communicating with Bluetooth Low Energy devices,
  on Android and iOS
version: 0.6.0+2
author: Paul DeMarco <paulmdemarco@gmail.com>
homepage: https://github.com/pauldemarco/flutter_blue

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  dio: '2.1.0'
  json_annotation: ^2.0.0
  json_serializable: ^2.1.1
  build_runner: ^1.3.1
  path_provider: '^0.4.1'
  convert: '^2.1.1'
  protobuf: '^0.13.12'
  rxdart: '^0.22.0'
  shared_preferences: ^0.4.2
  fl_chart: ^0.2.0



flutter:
  plugin:
    androidPackage: com.pauldemarco.flutterblue
    pluginClass: FlutterBluePlugin

dev_dependencies:
  flutter_test:
    sdk: flutter
